name: Update License Year

on:
  schedule:
    # Run at midnight UTC on January 1st every year
    - cron: '0 0 1 1 *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-license-year:
    name: Update License Year
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current year
        id: year
        run: echo "current_year=$(date +%Y)" >> $GITHUB_OUTPUT

      - name: Update LICENSE file
        run: |
          # Update copyright year in LICENSE file
          sed -i "s/Copyright (c) [0-9]* Cees-Jan Kiewiet/Copyright (c) ${{ steps.year.outputs.current_year }} Cees-Jan Kiewiet/" LICENSE

      - name: Update README.md file
        run: |
          # Update copyright year in README.md file
          sed -i "s/Copyright (c) [0-9]* Cees-Jan Kiewiet/Copyright (c) ${{ steps.year.outputs.current_year }} Cees-Jan Kiewiet/" README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update copyright year to ${{ steps.year.outputs.current_year }}"
          title: "Update copyright year to ${{ steps.year.outputs.current_year }}"
          body: |
            This PR updates the copyright year in LICENSE and README.md files to ${{ steps.year.outputs.current_year }}.
            
            This is an automated update that runs annually on January 1st.
          branch: update-license-year-${{ steps.year.outputs.current_year }}
          delete-branch: true
